name: Manual Deployment

on:
    workflow_dispatch:


env:
  targetEnv: dev

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pages: write
            id-token: write  
        environment: dev
              
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # Add your deployment steps here
            - name: Login
              uses: azure/login@v2.1.1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                enable-AzPSSession: true

            - name: Deploy to production
              uses: azure/arm-deploy@v1
              with:
                subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
                template: ${{ github.workspace }}/src/InfrastructureAsCode/main.bicep
                parameters: environment=${{ env.targetEnv }}
